Add setMinTimeBetweenSessionsMillis API
amplitude/unity-plugin pull request #56
Opened 2021-02-19 23:18 UTC by dantetam

I would like to review together and have someone test on their local iOS installation.

2021-02-20 00:16 UTC, haoliu-amp requested changes

2021-02-20 00:16 UTC, haoliu-amp commented on Assets/Amplitude/Amplitude.cs
> +    /// every eventUploadPeriodMillis milliseconds, or if the unsent event count exceeds the
indentation issue.

2021-02-20 07:09 UTC, haoliu-amp requested changes

2021-02-20 07:09 UTC, haoliu-amp commented on CHANGELOG.md
> +## 2.1.0 (Feb 19, 2021)
Also need to update `UnityLibraryVersion` in `Amplitude.cs`. Also we shouldn't include this change within this PR.

The right way to do it is to create a separate PR called `Prepare release x.x.x` by only updating the version and CHANGELOG. Please read the commit history.

2021-02-21 07:08 UTC, dantetam commented
Just looked at the suggestions, I will fix the PR. Going to make a PR for the Android libraries and test on both iOS and Android. 

I saw that there are different standards for semantic versioning. See [the iOS SDK documentation](https://github.com/amplitude/Amplitude-iOS/blob/main/CONTRIBUTING.md). This is fine and I will also look more deeply into the release and versioning process.

2021-02-21 17:10 UTC, closed without merging